-- View: DEV_DBM.INGESTION_METADATA.CONFIG_METADATA
-- Produces DDL strings for creating pipe and stream per table in the new model
-- Uses VW_METADATA as the source of truth

CREATE OR REPLACE VIEW DEV_DBM.INGESTION_METADATA.CONFIG_METADATA(
    PIPECREATE,
    CREATESTREAM,
    TARGETDB,
    RAWDB,
    TARGETSCHEMA,
    RAWSCHEMA,
    STAGE_FQN,
    PATH,
    FILE_FORMAT_FQN,
    DATABASENAME,
    SCHEMANAME,
    TABLENAME
) AS
WITH distinct_tables AS (
  SELECT DISTINCT
    DBNAME AS DATABASENAME,
    SCHEMANAME,
    TABLENAME,
    MAX(STAGE_FQN) AS STAGE_FQN,
    MAX(PATH) AS PATH,
    MAX(FILE_FORMAT_FQN) AS FILE_FORMAT_FQN
  FROM DEV_DBM.INGESTION_METADATA.VW_METADATA
  GROUP BY 1,2,3
)
SELECT
  'create or replace pipe '||DATABASENAME||'.RAW.PIPE_'||TABLENAME||' auto_ingest=true\n'
  ||'integration=''ZELISDATALAKEINTEGRATION_DEV'' as\n'
  ||'COPY INTO '||DATABASENAME||'.RAW.RAW_'||TABLENAME||'\n'
  ||'    FROM '''||STAGE_FQN||'/'||PATH||'''\n'
  ||'FILE_FORMAT=(FORMAT_NAME='''||FILE_FORMAT_FQN||''')\n'
  ||'MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE\n'
  ||'ON_ERROR = CONTINUE\n'
  ||'INCLUDE_METADATA = (RAW_ROW_CRE_DT = METADATA$START_SCAN_TIME, FILENAME = METADATA$FILENAME)\n'
  ||'PATTERN=''.*csv'';' AS PIPECREATE,

  'create or replace stream '||DATABASENAME||'.RAW.ST_RAW_'||TABLENAME||' on table '
  ||DATABASENAME||'.RAW.RAW_'||TABLENAME||' append_only = true;' AS CREATESTREAM,

  DATABASENAME AS TARGETDB,
  DATABASENAME AS RAWDB,
  'TARGET' AS TARGETSCHEMA,
  'RAW' AS RAWSCHEMA,
  STAGE_FQN,
  PATH,
  FILE_FORMAT_FQN,
  DATABASENAME,
  SCHEMANAME,
  TABLENAME
FROM distinct_tables;