-- Procedure: DEV_DBM.INGESTION_METADATA.CREATE_SCHEMAS_IF_NOT_EXISTS
-- Ensures <DB>.RAW and <DB>.TARGET schemas exist within a single database per feed

CREATE OR REPLACE PROCEDURE DEV_DBM.INGESTION_METADATA.CREATE_SCHEMAS_IF_NOT_EXISTS(
  DB_NAME VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
  EXECUTE IMMEDIATE ''CREATE SCHEMA IF NOT EXISTS ''||:DB_NAME||''.RAW'';
  EXECUTE IMMEDIATE ''CREATE SCHEMA IF NOT EXISTS ''||:DB_NAME||''.TARGET'';
  RETURN ''Successful'';
END';