-- Procedure: DEV_DBM.INGESTION_METADATA.ENSURE_CONTROL_TABLES
-- Ensures RAW control tables exist in <DB>.RAW

CREATE OR REPLACE PROCEDURE DEV_DBM.INGESTION_METADATA.ENSURE_CONTROL_TABLES(
  DBNAME VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
  EXECUTE IMMEDIATE ''CREATE SCHEMA IF NOT EXISTS ''||:DBNAME||''.RAW'';

  EXECUTE IMMEDIATE ''CREATE TABLE IF NOT EXISTS ''||:DBNAME||''.RAW.TASKEMAIL_NOTIFICATION_CONTROL (\n''||
    ''  TASKNAME STRING,\n''||
    ''  DBNAME STRING,\n''||
    ''  SCHEMANAME STRING,\n''||
    ''  QUERYTEXT STRING,\n''||
    ''  ERRORMESSAGE STRING,\n''||
    ''  RUNID NUMBER(38,0),\n''||
    ''  FIRST_ERROR_MESSAGE STRING,\n''||
    ''  COMLETEDTIME TIMESTAMP_LTZ(9),\n''||
    ''  IS_NOTIFIED NUMBER(38,0) DEFAULT 0\n''||
  '')'';

  EXECUTE IMMEDIATE ''CREATE TABLE IF NOT EXISTS ''||:DBNAME||''.RAW.MONITORINGTASKRUNFORFAILURE (\n''||
    ''  QUERY_ID STRING,\n''||
    ''  NAME STRING,\n''||
    ''  DATABASE_NAME STRING,\n''||
    ''  SCHEMA_NAME STRING,\n''||
    ''  QUERY_TEXT STRING,\n''||
    ''  CONDITION_TEXT STRING,\n''||
    ''  STATE STRING,\n''||
    ''  ERROR_CODE STRING,\n''||
    ''  ERROR_MESSAGE STRING,\n''||
    ''  SCHEDULED_TIME TIMESTAMP_LTZ(3),\n''||
    ''  QUERY_START_TIME TIMESTAMP_LTZ(3),\n''||
    ''  NEXT_SCHEDULED_TIME TIMESTAMP_LTZ(3),\n''||
    ''  COMPLETED_TIME TIMESTAMP_LTZ(3),\n''||
    ''  ROOT_TASK_ID STRING,\n''||
    ''  GRAPH_VERSION NUMBER(38,0),\n''||
    ''  RUN_ID NUMBER(38,0),\n''||
    ''  RETURN_VALUE STRING,\n''||
    ''  SCHEDULED_FROM STRING,\n''||
    ''  ATTEMPT_NUMBER NUMBER(38,0),\n''||
    ''  CONFIG STRING,\n''||
    ''  QUERY_HASH STRING,\n''||
    ''  QUERY_HASH_VERSION NUMBER(38,0),\n''||
    ''  QUERY_PARAMETERIZED_HASH STRING,\n''||
    ''  QUERY_PARAMETERIZED_HASH_VERSION NUMBER(38,0),\n''||
    ''  GRAPH_RUN_GROUP_ID STRING,\n''||
    ''  BACKFILL_INFO OBJECT\n''||
  '')'';

  EXECUTE IMMEDIATE ''CREATE TABLE IF NOT EXISTS ''||:DBNAME||''.RAW.EMAIL_NOTIFICATION_CONTROL (\n''||
    ''  FILE_NAME STRING,\n''||
    ''  STAGE_LOCATION STRING,\n''||
    ''  STATUS STRING,\n''||
    ''  FIRST_ERROR_MESSAGE STRING,\n''||
    ''  LAST_LOAD_TIME TIMESTAMP_LTZ(9),\n''||
    ''  LAST_NOTIFICATION_TIME TIMESTAMP_LTZ(9),\n''||
    ''  IS_NOTIFIED BOOLEAN DEFAULT FALSE\n''||
  '')'';

  RETURN ''OK'';
END';