-- Procedure: DEV_DBM.INGESTION_METADATA.ENSURE_STAGE
-- Creates external stage @<DB>.RAW.STG_<DataFeedName> if missing

CREATE OR REPLACE PROCEDURE DEV_DBM.INGESTION_METADATA.ENSURE_STAGE(
  DBNAME VARCHAR,
  DATAFEED_NAME VARCHAR,
  STORAGE_INTEGRATION VARCHAR,
  URL VARCHAR,
  FILEFORMAT_NAME VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
  stage_name STRING;
  exists_count INT;
BEGIN
  stage_name := :DBNAME||''.RAW.STG_''||:DATAFEED_NAME;
  EXECUTE IMMEDIATE ''CREATE SCHEMA IF NOT EXISTS ''||:DBNAME||''.RAW'';

  EXECUTE IMMEDIATE ''SHOW STAGES IN SCHEMA ''||:DBNAME||''.RAW'';
  SELECT COUNT(*) INTO :exists_count FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE UPPER("name") = UPPER(''STG_''||:DATAFEED_NAME);

  IF (NVL(:exists_count,0) = 0) THEN
    EXECUTE IMMEDIATE ''CREATE STAGE ''||stage_name||'' URL=''''||:URL||'''' STORAGE_INTEGRATION=''''||:STORAGE_INTEGRATION||'''' FILE_FORMAT=(FORMAT_NAME=''''||:DBNAME||''.RAW.''||:FILEFORMAT_NAME||'''')'';
  END IF;
  RETURN ''OK'';
END';